codesydney/eisteddfod

- about.html
- assets/css/custom.css
- assets/css/style.css
- blog.html
- causes.html
- index.html
Replaced the text in the about us section of the home page.
- Issue Title
> Refactored the text in about us section.

- assets/css/custom.css
- index.html
- Added the link to Stardom in the call to action buttons.
- 
- Issue Title
> Added link to Stardom and modified some layout.

- sponsorship.html
- hide the unused nav items
- Issue 13 sponsorship program hide nav items
- [x ] Code Formatted nicely (Prettier)
> issue 13 sponsorship program hide nave items

- sponsorship.html
- changed the title of the page to: "Be associated with the largest performing arts festival in Western Sydney"
- Issue Title
- [x ] Code Formatted nicely (Prettier)
> Issue 13 sponsorship programs

- about.html
- assets/css/custom.css
- contact.html
- index.html
- sponsorship.html
- syllabus.html
Removed some navigations
- Issue Title
> refactored navigation buttons across the page.

- assets/css/entries.css
- entries.html
- built the entries page instead of entry fees
- this page contains all the information about how to enter and entry fees
- Issue Title
> issue-8-entry-fees

- entries.html
- increased top margin for the paragraph "Phone only between 8:30 a.m. and 8 p.m. 7 days."
- Issue 8 entry fees
> issue-8-entry-fees-modify

- entries.html
- sponsorship.html
- replace syllabus with entries
- Issue 8 entry fees
> issue 8 entry fees change menu item

- assets/css/entries.css
- entries.html
- sponsorship.html
- changed sponsors section background to white
- changed font size of sponsorship page to 23px
- Issue 8 entry fees
> issue 8 entry fees implemente recommendation

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- index.html
- sponsorship.html
> Contact us

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- index.html
- sponsorship.html
- syllabus.html
> Refactored about us page

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- sponsorship.html
Adjusted the width of the title heading for the contact us page.
- Issue Title
> Refactor about us

- assets/css/custom.css
- index.html
- Changed the focus text color to a linear gradient of light and dark shades of purple
- changed the selection background to a shade of purple
- Issue 40 Change Focus text color and selection background color
> issue 40 change focus text color and selection background color

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- sponsorship.html
- Changed bread crumb color from orange to a light shade of purple
- Issue
> changed bread crumbs color to a light purple from orange"

- entries.html
- Added pdf icon to the syllabus link
- Added external link icon to stardom link
- Link icons
> add pdf and external link icons to the links

- assets/css/custom.css
- change the text fill on selection
- Issue 46
- [ x] No commented code
- [ x] Code Formatted nicely (Prettier)
> issue-46 completed

- about.html
- assets/css/custom.css
- assets/css/entries.css
- assets/css/style.css
- contact.html
- entries.html
- index.html
- sponsorship.html
- syllabus.html
- moved inline styles to custom.css
- refactored some part of about us and contact
- changed "Enrol" to "Enter"
- Fixed the map to be Parramatta
- Issue update styles
> update style and refactor some pages

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- index.html
- sponsorship.html
Applied changes to the navigation tabs and removed some fields from the quick links
- Issue Title
> Applied changes as requested by Sue

- entries.html
- made the email and phone numbers clickable
- Issue
> set email and phone as clickable links

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- index.html
- sponsorship.html
Updated the footer section
- Issue Title
> Updated footer section

- assets/css/custom.css
Fixed the stat circle to ensure the content fits in the circle.
- Issue Title
Stat circle is too small for the content
> Fixed the stat circle issue

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- index.html
- sponsorship.html
- volunteer.html
- Built volunteer page
- updated the nav item to open volunteer page
- Issue 61 volunteer page
> issue 61 volunteer page

- contact.html
- removed the volunteer information from contact page
- Issue remove volunteer info from contact
> remove volunteer from contact

- about.html
- contact.html
- entries.html
- index.html
- sponsorship.html
- volunteer.html
- Changed "Volunteering" to "Volunteer"
- Issue Title
> Volunteering to Volunteer

- about.html
- assets/css/custom.css
- entries.html
- index.html
- sponsorship.html
- volunteer.html
- Made a new badge for sponsor
- updated the sponsor area of all relevant pages
- made the "Illuminating" color a gradient of white and purple 
- Issue custom badge
> make custom badge

- assets/css/custom.css
- made the text with gradient color white when selected
- Issue Title
> fix selection text

- assets/css/custom.css
- index.html
Added testimonials section to showcase the organization's work and reputation.
- Issue Title
> Added Testimonials section

- about.html
> Fixed typo error from the committee title

- index.html
Replaced the stat circle text from the homepage to properly convey message.
- Issue Title
> Replaced the stat circle text from the homepage.

- assets/css/custom.css
Replaced the preloader color shade to match the color pallete of the Eidsteddfod Parramatta website.
- Issue Title
> replaced preloader color

- assets/css/custom.css
Fixed the testimonial section layout that overlaps with the other content.
ISSUE_TESTIMONIALS_CONTENT_OVERLAPS
- Issue Title
https://github.com/codesydney/eisteddfod/issues/94
> Fixed testimonail content issue

- volunteer.html
- restored volunteer.html from my local machine
- Issue fix volunteer.html footer section
> volunteer upload

- index.html
Randomized the color of the testimonial card,
- Issue Title
> Dev 001 what people say about us page

- assets/css/custom.css
- index.html
Added a media query for ipad device to properly render the homepage content.
https://github.com/codesydney/eisteddfod/issues/72
- Issue Title
IPad and IPhone Paragraphs and/or titles gap.
> Added media query for ipad device in home page.

- about.html
- assets/css/custom.css
- contact.html
- index.html
Fixed the layout issues with apple devices.
The title text in the About Us page breaks to new line 
IPad and IPhone Paragraphs and/or titles gap.
- Issue Title
> Mobile responsive view for apple devices

- assets/css/custom.css
- contact.html
Integrated EmailJS, added built in HTML 5 form validation controls and Toast Notification.
- Integrate EmailJS with Contact Form 
- Issue Title
- Show form error on top of the form or under each fields
> Integrated EmailJS to contact page.

- contact.html
Added the clear fields functionality after clicking the submit button.
- Issue Title
> Added clear feature after submitting the form

- assets/css/custom.css
- sponsorship.html
- add sponsors on the sponsorship page
- Issue 93
> issue 93 add sponsors

- about.html
- sponsorship.html
- volunteer.html
Replaced the text across the page.
- Issue Title
GET INVOLVED: Sponsorship
Replace the text go to the ‘Get Involved’ page from the about us page
Get Involved: Changes in text content from the volunteer page
> Made changes to text

- contact.html
Replaced the map in the contact page to reflect on the venue's location.
- Issue Title
Replace the map in the contact page
> Replaced the map in the contact page

- assets/css/custom.css
> Set default size to span

- assets/css/custom.css
> Reduced font size

- about.html
- assets/css/custom.css
> Replaced span with div

- about.html
- assets/css/custom.css
> Revert changes

- assets/css/custom.css
Fixed the issue with the navigation button that was hidden when the website is opened in iphone device. Adjusted the height of the testimonials card.
https://github.com/codesydney/eisteddfod/issues/112
- Issue Title
> Added the navigation button in iphone device.

- about.html
- entries.html
- index.html
- volunteer.html
Removed the "Our Current Sponsors" from the home page, about us page, volunteer page and entries page.
https://github.com/codesydney/eisteddfod/issues/128
- Issue Title
> Removed Our Current Sponsors from 4 pages.

- assets/css/custom.css
- sponsorship.html
- adjusted sponsor rate
- adjusted some wording in benefits
- Issue Title
> issue 121 adjust sponsors rate

- assets/css/custom.css
- fixed the text with gradient color not displaying properly in safari on mobile devices
- Issue Title
> issue 177 fix broken text in safari mobile

- about.html
- blog-details.html
- blog.html
- causes-details.html
- causes.html
- contact.html
- entries.html
- event-details.html
- index.html
- privacy-policy.html
- sponsorship.html
- syllabus.html
- volunteer.html
This is for issue 120 that replace the privacy policy link so that it opens the privacy policy pdf file
- Issue Title
> #120 replace the privacy policy and link to privac policy v1 pdf file

- sponsorship.html
- Changed the texts as outline in the issue #142.
- Issue 142
> issue 142 update texts in the sponsorship page

- assets/js/custom.js
- Made the transition on committee members area to be 10000ms
- Issue Title
> issue 139 fix transition speed

- assets/css/custom.css
- assets/css/entries.css
- assets/css/style.css
- entries.html
- sponsorship.html
- volunteer.html
- Reduces the outer gutter size
- Reduced the white spaces between different parts of the page like section, header and content.
- Used webflow website as a guide
- Issue Title
> issue 141 reduce white spaces

- assets/css/custom.css
- index.html
- Add a compact version of sponsors in the home page
- Issue Title
> issue 133 compact sponsors section on home page

- index.html
- add the word "our" to "View all of our Sponsors"
- Issue Title
> fix a spelling on home page

- entries.html
- fix footer overlap in Entries page
- Issue Title
> fix footer overlap

- assets/css/custom.css
- entries.html
- index.html
- sponsorship.html
- volunteer.html
- added a new container
- This container will be for content and separate from the container of the header and footer.
- Issue add a new container
> add new container

- entries.html
- volunteer.html
Corrected typographical error in some text.
- Issue Title
> Corrected text across the website.

- index.html
> fixed image path

- assets/css/custom.css
- entries.html
- sponsorship.html
- volunteer.html
- Changed the orange line before "Quick Links" to blue
- changed the orange bottom border on hover of quick links to blue
- Add copyright text on sponsorship, volunteer and entries pages
- Issue 95
> issue 95 and more

- contact.html
- sponsorship.html
Sue has requested to update the sponsorship silver category and the contact details. 
- Issue Title
> Minor updates

- index.html
- sponsorship.html
Added new bronze sponsors, initiated text removals in the testimonials section and the covid safe plan as requested.
- Issue Title
> Modified the index page and sponsorship page.

- entries.html
Altered a few text in the entries.html
- Issue Title
> Added further changes to entries.html

- sponsorship.html
The client has requested to update the sponsorship page.
n/a
n/a
- Issue Title
> updated sponsorship page

- index.html
> Modified index page

- about.html
- assets/css/custom.css
- contact.html
- entries.html
- privacy-policy.html
- sponsorship.html
- volunteer.html
Modified the text and replaced some key information for this year's Parramatta Eidsteddfod event. I added a small css code to change the color and positioning of the contact details.
Before:
After:
nil
- Issue Title
> Modified text and added a css style for the contact details

- contact.html
- entries.html
- index.html
- volunteer.html
> Replaced Eisteddfod's email
